[package]
name = "whatchanged"
version = "0.1.0"
authors = ["dave <dave@cyllective.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data-encoding = "2.2.0"
ring = "0.17.0-alpha.1"
colored = "1.9"
